name: Testy backendu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalacja zależności
        run: npm install

      - name: Testy jednostkowe
        run: npm run test

      - name: Testy integracyjne
        run: npm run test:e2e